name: brubaker_homeapp
description: "A new Flutter project."

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  flutter_rating_bar: ^4.0.1
  http: ^1.5.0
  flutter_colorpicker: ^1.1.0
  google_fonts: ^6.3.0
  image_picker: ^1.2.0
  video_player: ^2.10.0
  chewie: ^1.12.1
  uuid: ^4.5.1
  animate_do: ^4.2.0
  confetti: ^0.7.0
  shared_preferences: ^2.5.3
  sensors_plus: ^6.1.2
  provider: ^6.1.5
  crypto: ^3.0.2
  app_links: ^4.0.0
  url_launcher: ^6.1.10
  flutter_dotenv: ^5.1.0
  flame: ^1.18.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.13.1
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/restaurants/
    - assets/cat.png
    - assets/modes/
    - assets/tracks/
    - assets/images/toad.png
  fonts:
    - family: Cinzel
      fonts:
        - asset: fonts/Cinzel-Regular.ttf

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/icon/icon.png"
